# Generated by Django 4.1.6 on 2023-02-24 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_payment_alter_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Order recived', 'Order recived'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered')], default='Order recived', max_length=20),
        ),
    ]
