# Generated by Django 4.1.5 on 2023-01-31 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wishlist", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="wishlist_item",
            old_name="cart",
            new_name="wishlist",
        ),
    ]
