# Generated by Django 4.1.6 on 2023-02-24 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0003_wishlists'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlists',
            old_name='Product',
            new_name='product',
        ),
    ]
