# Generated by Django 4.1.5 on 2023-01-21 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cart",
            old_name="card_id",
            new_name="cart_id",
        ),
    ]
