# Generated by Django 4.1.5 on 2023-01-19 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_userprofile"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="account",
            options={"verbose_name": "User", "verbose_name_plural": "Users"},
        ),
    ]
