# Generated by Django 4.1.4 on 2023-01-28 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_account_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="city",
            field=models.CharField(default="default.jpg", max_length=30),
        ),
    ]
